{% set name = "game" %}
{% set version = "0.0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

build:
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv
    number: 0
    entry_points:
        - game = game.main:main