{% set name = "kimeco" %}
{% set version = "1.0.4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    path: .

build:
    noarch: python
    skip: true  # [not linux]
    script: {{ PYTHON }} -m pip install . -vv --no-deps
    number: 0
    entry_points:
        - kmo = kimeco.main:main
        - kmoui = kimeco.gui.kimecoapp:main
        - kmopp = kimeco.postprocessing.postprocess:main

requirements:
    host:
        - python >=3.10
        - pip
        - setuptools >=61.0
        - wheel
    run:
        - python >=3.10
        - ase >=3.22.1
        - cantera >=3.0.0
        - numpy >=2
        - pandas >=2.2
        - sqlalchemy
        - sqlalchemy-utils
        - dash
        - scipy >=1.10
        - plotly >=5
        - pint
        - mess-static

test:
    requires:
        - pytest
    imports:
        - kimeco
        - kimeco.core
        - kimeco.database.kimeco_db
        - kimeco.gui.kimecoapp
        - pint
    commands:
        - kmo --help
        - kmoui --help
        - kmopp --help

about:
    home: https://github.com/sandialabs/KiMecO
    summary: Kinetic Mechanism Optimizer
    license: MIT

extra:
    recipe-maintainers:
        - csoulie