{% set name = "kimeco" %}
{% set version = "0.0.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

build:
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv
    number: 0
    entry_points:
        - kmo = kimeco.main:main
        - kmoui = kimeco.gui.gameapp:main