[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["build", "dist", "kimeco.egg-info", "dev_tests*"]

[project]
name = "kimeco"
version = "1.1.7"
authors = [
  { name="Clement Soulie", email="csoulie@sandia.gov" }
]
maintainers = [
  { name="Clement Soulie", email="csoulie@sandia.gov" }
]
description = "KIMECO"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Chemistry"
]
dependencies = [
    "ase>=3.22.1",
    "cantera>=3.0.0",
    "numpy>=2",
    "pandas>=2.2",
    "sqlalchemy",
    "sqlalchemy-utils",
    "dash",
    "scipy>=1.10",
  "plotly>=5",
  "pint",
  "pyarrow>=14"
]

[project.optional-dependencies]
test = ["pytest>=9.0.2"]
automech = [
    "autoio>=0.2026.0",
    "autochem>=0.2025.0,<2.0.0",
    "mako>=1.3.10",
    "more-itertools>=10.8.0",
    "networkx>=3.3",
    "pint>=0.25",
    "pyparsing>=3.2.5",
    "pyyaml>=6.0.3",
    "qcelemental>=0.29.0",
    "rdkit>=2025.9.1",
    "scipy>=1.12",
    "xarray>=2023.8",
]

[project.scripts]
kmo = "kimeco.main:main"
kmo_start = "kimeco.gui.kmo_start:main"
kmoui = "kimeco.gui.kimecoapp:main"
kmopp = "kimeco.postprocessing.postprocess:main"
